### ISSUE TITLE
Kirjautumisen ja rekisteröinnin salasanat

### ISSUE THREAD

**Issue by Backwoods7** [Fin3er/Matopeli_vsk_ryhma6#2]
Nämä voisi ainakin piilottaa syöttövaiheessa (input type="password"). Jos ehtii niin voi katsoa myös jos saisi muuten turvattua.

**Comment by Fin3er** [comment]
Joo Jaakkohan sanoi, ettei salasanaa saa lähettää ilman salausta verkon yli, eli joku hash tuohon pitää keksiä.
